function gen_plots(save_str)
% Generates plots for RUNKAPPAPLOT

%%
% Load run data directly into variable space
load(save_str); %#ok<LOAD>
n_alg = length(lgd);
n_symb = length(symb);

% Initialize figures and axes
fg = cell(1,3);
ax = cell(1,3);
for k = 1:3
    fg{k} = figure;
    fg{k}.Position(3) = 700; % slightly stretches horizontally
    ax{k} = gca;
    hold on;
end

% Plot data
for j = 1:n_alg
    k = mod(j,n_symb) + 1;
    plot(ax{1}, condXX, loss_ortho(:,j),...
        symb{k}, 'Color', alg_cmap(j,:), 'MarkerSize', 10, 'LineWidth', 1);
    plot(ax{2}, condXX, rel_res(:,j),... 
        symb{k}, 'Color', alg_cmap(j,:), 'MarkerSize', 10, 'LineWidth', 1);
    plot(ax{3}, condXX, rel_chol_res(:,j),...
        symb{k}, 'Color', alg_cmap(j,:), 'MarkerSize', 10, 'LineWidth', 1);
end
% Plot comparison lines
plot(ax{1}, condXX, eps*condXX, 'k--', condXX, eps*(condXX.^2), 'k-')
plot(ax{3}, condXX, eps*condXX, 'k--', condXX, eps*(condXX.^2), 'k-')

% Make plots pretty and save them
plot_str = {'loss_ortho', 'rel_res', 'rel_chol_res'};
for k = 1:3
    % Aesthetics
    set(ax{k}, 'Yscale', 'log', 'Xscale', 'log',...
        'XGrid', 'on', 'YGrid', 'on',...
        'XMinorGrid', 'off', 'YMinorGrid', 'off',...
        'FontSize', 10);
    
    % X-axis label
    xlabel(ax{k}, '$\kappa(\mathcal{X})$', ...
        'Interpreter', 'Latex', ...
        'FontSize', 10)
    
    % Legends and titles
    if k == 1
        lgd_loo = lgd;
        lgd_loo{end+1} = '$O(\varepsilon) \kappa(\mathcal{X})$'; %#ok<*AGROW> 
        lgd_loo{end+1} = '$O(\varepsilon) \kappa^2(\mathcal{X})$';
        legend(ax{k}, lgd_loo, 'Location', 'BestOutside', ...
            'Interpreter', 'Latex', ...
            'FontSize', 10, ...
            'EdgeColor','none', ...
            'Color','none');
        title(ax{k}, ...
            ['Loss of Orthogonality: ' ...
            '$\Vert I - \bar\mathcal{Q}^T \bar\mathcal{Q}\Vert$'], ...
            'Interpreter', 'Latex', ...
            'FontSize', 10);
        movegui(fg{1},'northwest')
    elseif k == 2
        legend(ax{k}, lgd, 'Location', 'BestOutside', ...
            'Interpreter', 'Latex', ...
            'FontSize', 10, ...
            'EdgeColor', 'none', ...
            'Color', 'none');
        title(ax{k}, ...
            ['Relative Residual: ' ...
            '$\Vert \mathcal{X} - ' ...
            '\bar\mathcal{Q}\bar\mathcal{R}\Vert/\Vert X\Vert$'], ...
            'Interpreter', 'Latex', ...
            'FontSize', 10);
        movegui(fg{2},'northeast')
    elseif k == 3
        lgd_chol = lgd;
        lgd_chol{end+1} = '$O(\varepsilon) \kappa(\mathcal{X})$'; %#ok<*AGROW> 
        lgd_chol{end+1} = '$O(\varepsilon) \kappa^2(\mathcal{X})$';
        legend(ax{k}, lgd_chol, 'Location', 'BestOutside', ...
            'Interpreter', 'Latex', ...
            'FontSize', 10, ...
            'EdgeColor', 'none', ...
            'Color', 'none');
        title(ax{k}, ...
            ['Relative Cholesky Residual: ' ...
            '$\Vert \mathcal{X}^T \mathcal{X} - ' ...
            '\bar\mathcal{R}^T \bar\mathcal{R}\Vert/ ' ...
            '\Vert \mathcal{X}\Vert^2$'], ...
            'Interpreter', 'Latex', ...
            'FontSize', 10);
        movegui(fg{3},'south')
    end

    % Save figures
    save_str = sprintf('%s/%s', dir_str, plot_str{k});
    if options.save_eps
        saveas(fg{k}, save_str, 'epsc');
    end

    if options.save_fig
        savefig(fg{k}, save_str, 'compact');
    end
end